import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const WhatsAppButton = () => {
  const phoneNumber = "8287626652"; // Replace with your phone number

  const style = {
    position: 'fixed',
    bottom: '50px',
    right: '100px',
    backgroundColor: '#25D366', // WhatsApp color
    color: 'white',
    // padding: '10px',
    borderRadius: '50%',
    textDecoration: 'none',
    textAlign: 'center',
    fontSize: '16px',
    width: '50px',
    height: '50px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer'
  };

  return (
    <a href={`https://wa.me/${phoneNumber}`} target="_blank" rel="noopener noreferrer" style={style}>
      <img 
      className="whatsapp"
      src="https://res.cloudinary.com/dovcumkby/image/upload/v1702374957/icons8-whatsapp_eq9jqx.gif"></img>
    </a>
  );
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <WhatsAppButton />
      </body>
    </html>
  );
}
